cluster_weekday_blurb = '''In order to better visualize docks that had similar usage patterns on weekdays, K-Means Clustering was performed to group docks together and visualize average bike availability over the course of a weekday. For the purpose of clustering, each unique dock was an observation in the data with an average proportion of bike availability for each hour of the day providing 24 total features. An elbow plot was used to determine the number of clusters based on the drop in inertia for each additional cluster. Inertia is calculated by measuring the distance between each data point and its centroid, squaring this distance, and summing these squares across each cluster. Based on the elbow plot, the optimal number of clusters was determined to be 7 to avoid overfitting. The line graphs show the change in average availability throughout a day within a cluster. Clear usage trends can be seen within clusters. In morning hours, ‘receiving’ docks located near offices or transit hub locations see a spike in bike availability as commuters go to work. Likewise, ‘sending’ docks see a sharp drop in bike availability as commuters go to work. The reverse of both trends occurs in the evening as commuters return home from work. There are also some docks that are less affected by commuter trends that see more random usage.
'''

cluster_weekend_blurb = '''The same K-Means Clustering method was used for weekend clustering. Based on weekend usage patterns the trends are less distinct than weekday patterns. With the absence of commuter patterns, the average availability appears to be more randomized. However, some mild trends in availability can be observed in the afternoon as user leisure rides are taken during the weekends.'''

rebalance_time_blurb = '''The rebalancing rides that were considered were those whose lag time between the bike transfer and the next ride was less than 2 hours. Of these rebalanced rides, there are 2 clear peaks which occur during commuting times from 8-9 AM and 5-6 PM. Our hypothesis is that rebalancing is being done after each wave of commuters rides either to or from work during these commuting times to allow for the next wave of commuters to have accessible bikes. There is also rebalancing being done in between these times and a lack of rebalancing being done at night.'''

rebalance_dist_blurb = '''The trip distances (measured in Manhattan distance) for all rebalanced rides are shown, with a peak at 0.5 miles. At least half of the rebalanced rides were less than 2 miles, with a large concentration below 1 mile. These rebalanced trip distances were considered in the constraints we used to develop our optimal rebalancing strategy.'''

rebalance_3d_weekday_blurb = '''This plot shows the top 300 most prevalent rebalancing routes. During the weekdays, there are many rebalancing rides in Alphabet City. It can be inferred that the cause of this imbalance is commuters within Alphabet City travel to/from work or the nearest public transit location. Due to high residential density and the distance to the nearest subway station this is a high use area. Similarly, there are many rebalancing rides from Penn Station to various locations. It can be inferred that due to the business density around Penn Station it is a ‘receiving’ station for many commuter rides in the morning. To ensure bike docks are available for different waves of commuters, rebalancing is required to maintain available docks in the area. Similar trends can be seen around the other Central Business Districts that receive a large number of bikes during commuting hours.'''

rebalance_3d_weekend_blurb = '''In comparison to the weekdays, the demand for rebalancing in Alphabet City is much lower during the weekends. In addition, there are fewer rebalancing rides throughout the Central Business District since there are no waves of commuters going to and from work. On the other hand, there is a significantly higher demand for rebalancing at the southern end of Central Park during the weekends as opposed to during the weekdays.'''
